services:
  postgres_main:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "api_adesoes"
    volumes:
      - /usr/local/postgres_producer_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  postgres_consumer:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cobrancas_consumer"
    volumes:
      - /usr/local/postgres_consumer_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin_main:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "paulo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    networks:
      - postgres-compose-network

  rabbitmq_main:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5672:5672"
    volumes:
      - ./rabbitmq-dados:/var/lib/rabbitmq/
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5
    
networks: 
  postgres-compose-network:
    driver: bridge
